{"uuid": "c9c4a75d-faad-4ada-9437-742b5db25689", "children": ["7d2bfbd3-c557-497a-9750-7f342277415a"], "befores": [{"name": "setup", "status": "passed", "start": 1739096079405, "stop": 1739096084826}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\91992\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\91992\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\91992\\PycharmProjects\\OHRM_101\\Testcases\\conftest.py\", line 26, in setup\n    driver.quit()\n  File \"C:\\Users\\91992\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 193, in quit\n    self.service.stop()\n  File \"C:\\Users\\91992\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 149, in stop\n    self.send_remote_shutdown_command()\n  File \"C:\\Users\\91992\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 134, in send_remote_shutdown_command\n    if not self.is_connectable():\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\91992\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 123, in is_connectable\n    return utils.is_connectable(self.port)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\91992\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 101, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\91992\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\socket.py\", line 843, in create_connection\n    exceptions.clear()  # raise only the last error\n    ^^^^^^^^^^^^^^^^^^\n"}, "start": 1739096084836, "stop": 1739096087361}], "start": 1739096079405, "stop": 1739096087361}